### ISSUE TITLE
Question about probabilities

### ISSUE THREAD

**Issue by microplasticos** [ramsy0dev/unlisted#14]
If I understand correctly, this script generates a random ID and checks if it's valid, right? The problem is that there are 64^11 possible IDs, and it would take 584,942,417,355 seconds at 4 IDs generated per second, which makes the probability of finding the correct ID negligible. Did I understand correctly? Thank you.

**Comment by ramsy0dev** [comment]
I will assume that you are not really going to use it to actually find an unlisted video, because yeah it's impossible but it's possible to build a script that does that and that's the hole point.
